### PR TITLE
 feat(1650): Improve eslint rules

### PR DESCRIPTION
**Pull request by wdstar**
## Context

This PR improves the existing eslint rules and adds `prettier`.

## Objective

- add useful warning rules.
- add `prettier` for source code formatting.
- format `index.js` by `prettier`.

## Note

When we first use this eslint rules, we must fix most of the errors by hitting `eslint --fix ` and fix the remaining errors manually.

## References

- https://github.com/screwdriver-cd/screwdriver/issues/1650

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by tk3fftk — COMMENTED** [review]
Is this braking change?

**Review by tk3fftk — APPROVED** [review]
changes are LGTM:+1:

**Comment by wdstar** [comment]
> Is this braking change?

Um... I can't judge it.

**Review by tkyi — APPROVED** [review]

**Comment by tkyi** [comment]
I think it should be okay to pull in as non-breaking

**Pull request merged**
